version: '3.4'

services:
  dynamodb-spring-data-rest-sb:
    image: dynamodb-spring-data-rest-sb
    build: .
    ports:
      - 8080:8080
    environment: 
      AMAZON_DYNAMODB_ENDPOINT: http://dynamodb:8000

  dynamodb:
    image: amazon/dynamodb-local
    

